[versions]

picocontainer="2.15.2"
codesize="1.3.1"
nexus-publish = "2.0.0"
ben-manes-versions = "0.53.0"
eclipse-jdt = "3.44.0"
kotlin = "2.3.0"
bcel = "6.11.0"

[libraries]

picocontainer = { module = "org.picocontainer:picocontainer", version.ref = "picocontainer" }
codesize = { module = "net.sf.robocode:codesize", version.ref = "codesize" }
eclipse-jdt = { module = "org.eclipse.jdt:org.eclipse.jdt.core", version.ref = "eclipse-jdt" }
kotlin-stdlib = { module = "org.jetbrains.kotlin:kotlin-stdlib", version.ref = "kotlin" }
bcel = { module = "org.apache.bcel:bcel", version.ref = "bcel" }

[bundles]

[plugins]

nexus-publish = { id = "io.github.gradle-nexus.publish-plugin", version.ref = "nexus-publish" }

# ./gradlew dependencyUpdates -Drevision=release
ben-manes-versions = { id = "com.github.ben-manes.versions", version.ref = "ben-manes-versions" }
