[versions]

picocontainer="2.15"
codesize="1.3.0"
jreleaser = "1.18.0"
ben-manes-versions = "0.51.0"
eclipse-jdt = "3.39.0"
kotlin = "2.0.20"
bcel = "6.10.0"

[libraries]

picocontainer = { module = "org.picocontainer:picocontainer", version.ref = "picocontainer" }
codesize = { module = "net.sf.robocode:codesize", version.ref = "codesize" }
eclipse-jdt = { module = "org.eclipse.jdt:org.eclipse.jdt.core", version.ref = "eclipse-jdt" }
kotlin-stdlib = { module = "org.jetbrains.kotlin:kotlin-stdlib", version.ref = "kotlin" }
bcel = { module = "org.apache.bcel:bcel", version.ref = "bcel" }

[bundles]

[plugins]

jreleaser = { id = "org.jreleaser", version.ref = "jreleaser" }

# `./gradlew dependencyUpdates`
ben-manes-versions = { id = "com.github.ben-manes.versions", version.ref = "ben-manes-versions" }
