name: Java CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Gradle
        run: ./gradlew build

      - name: robocode.core test artifacts
        if: always()
        uses: actions/upload-artifact@v6
        with:
          name: robocode.core-test-result
          path: robocode.core/build/reports/tests/test

      - name: robocode.host test artifacts
        if: always()
        uses: actions/upload-artifact@v6
        with:
          name: robocode.host-test-result
          path: robocode.host/build/reports/tests/test

      - name: robocode.tests test artifacts
        if: always()
        uses: actions/upload-artifact@v6
        with:
          name: robocode.tests-result
          path: robocode.tests/build/reports/tests/test

      - name: setup binary artifact
        uses: actions/upload-artifact@v6
        with:
          name: robocode-setup
          path: build/robocode-*-setup.jar